name: Keep App Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: curl https://real-time-chat-app-o18l.onrender.com
